sudo: required

services:
  - docker

language: go

go:
- 1.9.3

env:
  global:
  - secure: LvNg7kBLWSZWJgjlA87soqjUaqu3l/zMzKtm2Ty+seCWQbhmJOsR6ov2XvpHAHawb4hB4NlxUhXPNlTPHloLMV+ofp6VCsPloRUjboLQHn+dyivD2XhrHUBTyCBN0bUQb/4giEO7DjyVGjTBHBTOWSaBZh4046RHR6I7OelTkFdMZf4k03h0OHzSzfe7MKAqa672QFI4A0d8qGkZVrbbhekhBY3uZv3jurkYgXegDjS8hFPn3HWdSZS3wTSTJUqMlwf/1ZLvOiZ1/jGhY3u03xjkLMsWV052kUke7k1WB//OmZomejXSU7/Tl5rPwALlQEDkIJ4YOot5R8CZpNRgMltT/ocqtPGH/YeE2OGPX1AeT3S/QAHzmoJmi8IfyKsvWCf2gpX1vKCDB0xJfkiU6kdn4hCJfj0AStHHD5YTw8D1JDiZll+24Z4vrd4ZQPVJeABt+EJX4VVidmoUeE/iaStiYqpokRzleBXRbWXyKuEpW9jv03WAOx3w8TtE1Cw+UBIA8NdrFSXBmzG4mRpMIUkbUguLXA5YKxWwIslamSW+II54NI9AB6THDv3xuEfIYhSvd5BdiIiVqgddhQXO0ybzXMRNPLrg/ocNksh3fLFn/y1jyKXpeh1mAVfxRIFVfHYKGAleG5570jFP5Wtospfef4OqbLN9Wm171wr8cfk=
  - secure: t41ftHvK+6R6+dQF/4tyQmegsJsljblF4DCdGEKam2DmTvMlFLeLkpfh6fw+nNXjBmPa+iSeq5eno3e9BCbt7a5r2Vzm0IM8gtXkHaObKU8oUFhkJp7oa60g3/RG9h3LnAd1dHPGs5wg7mNYATnDZQ/mXU/+cyi2mn+srabPDEdNjL/1nswet4KkiKT01VdIvMO5PGlrbui5wz035y9wVBS/CG9JAdyBWjqfqPR8yM1G0RAL+TVrvvkrbgLEa5zPSLX95cZzRo0CfD+1Br4VgNSjwtcMSN1EPJilsJsj5t26MB+/Jz38K7M+iTx9qqnjet2eSLYByDxoCWH3E9dve22HNu2w9YEXELrzo3odcoegGo2RL4lHj8wb6RRydPF2eD7Di8vowznnKpRWuinZDvXL7YBO94sI8BoU4fLqcg8+t1xn7JU2Phw3z3eBg61rIpSgr07wcptsIX372rbOEA8qT8lR+FWN+BCe51yoPySYPlP7PrIR5L4sWnGGad/T0f64rqjhBhBwA0fYXnddeFXy5PUv1XGtwSUsRhtiZdZgDNfUXzhYXRGG2eCf8IvJRvzLrXDMwduZFJy4mm/6i5XFCCWXuB0L9fNVkkuK6JmmSoUPppoJVPXAD9YHqe2fXur1TZ8MjynGGX75fyA+LkVRNSTWx+IX4zzUh7dQYE8=

before_install:
- env GOOS=linux GOARCH=amd64 go build ./cmd/cli
- docker build -t "nielsdenissen/flink-deployer:$TRAVIS_BRANCH" .

script:
- sh test-with-coverage.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD";
  docker push "nielsdenissen/flink-deployer:$TRAVIS_BRANCH";
  if [ "${TRAVIS_BRANCH}" == "master" ]; then docker tag nielsdenissen/flink-deployer:$TRAVIS_BRANCH nielsdenissen/flink-deployer:latest; docker push nielsdenissen/flink-deployer:latest; fi
